/*---------------------------------------------------------------------------*/
/* Akalon RTOS                                                               */
/* Copyright (c) 2011-2015, Dasa Dahanayaka                                  */
/* All rights reserved.                                                      */
/*                                                                           */
/* Usage of the works is permitted provided that this instrument is retained */
/* with the works, so that any entity that uses the works is notified of     */
/* this instrument.                                                          */
/*                                                                           */	
/* DISCLAIMER: THE WORKS ARE WITHOUT WARRANTY.                               */
/*                                                                           */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/
/*                                                                           */
/* File Name       : void_syms.c                                             */
/* Description     : Void Symbol List                                        */
/* Notes           : Was seperated to this file to avoid linker issues with  */
/*                   actual symbol list generated by gen_symbols             */
/*                                                                           */
/*---------------------------------------------------------------------------*/
#include <akalon.h>
#include <cli.h>

func_t   sym_funcs[] = {{0,NULL}} ;
var_t    sym_vars[]  = {{0,NULL}} ;





